import './global.css';
import Link from "next/link";

export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="next-app-layout">
          <header className="header">
            <div className="container">I am Header</div>
          </header>
          <div className="container layout-body">
            <div className="sidebar">
              <nav >
                <Link href="/react-app" className='nav-item'>React-app</Link>
                <Link href="/remix-app" className='nav-item'>Remix-app</Link>
                {/* <Link href="/svelte-app" className='nav-item'>Svelte-app</Link>
                <Link href="/chat-app" className='nav-item'>Chat-app</Link> */}
              </nav>
            </div>
            <div className="page-body">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
